roblox-ts/roblox-ts

- src/class/Transpiler.ts
This adds transpiler support for the modulo operator (`%`), which currently causes a compilation error.
This fixes #37
> Add modulo operator support

- include/RuntimeLib.lua
- src/class/Compiler.ts
- src/class/Transpiler.ts
This adds a new function to the RuntimeLib, `TS.import`.
`TS.import` takes a root instance or service name, then a variable number of arguments used to traverse to the desired instance. This is then loaded with `require` and returned.
If the instance can't be found, an error is thrown since there would be lots of type issues if the execution were to continue.
Closes #43
> Replace direct imports with waits using TS.import

- src/class/Compiler.ts
- src/class/Transpiler.ts
After #43 was fixed, two things were left out.
In some instances, imports were still being wrapped with `require`, and in another instance, not all parts of the imported path were included.
> Patch bug from fix of #43

- src/class/Transpiler.ts
Switch statements previously would not compile properly when returning out of them. Now they do!
The problem was that `${fallThroughVar} = true;` would be appended no matter what, even after a return statement.
```ts
function t(k : string) : number {
switch (k) {
case "a:":
case "Hello":
print("Nope")
return 1;
default:
print("Soup")
return 2;
}
}
t("a:")
```
By the way, I just started TypeScript today so please look very carefully at my submitted code!
> Fix Switch Statements with Return

- src/class/Transpiler.ts
This uses the solution as described in #55. The `_getters` and `_setters` are now direct members of class declarations. When a given class does not have getters/setters, but it inherits from a class with them, then the super class's `_getters` and `_setters` tables are used, and the custom `__index` and `__newindex` functions are used as well.
This example illustrates different facets of these changes:
```TypeScript
class RootTest {
get test() {
return "Test"
}
}
class Test1 extends RootTest {
test = super.test + "Test1"
}
class Test2 extends Test1 {
test = "Test2"
}
class Test3 extends Test1 {
otherTest = "Test3"
}
class Test4 extends RootTest {
get newTest() {
return "Test4"
}
set newTest(_value) { }
}
print(new RootTest().test) // Expected: "Test" Actual: "Test"
print(new Test1().test) …
```
> Fix inheritance issues with custom accessors

- src/class/Transpiler.ts
- Shortened `.new()` implementation to 1 line
- Made constructors return `self`
> Shorten `new` functions

- src/class/Transpiler.ts
It looks like you may have written the comparison before adding the `slice` method. It should be running for any length greater than 0 now that the `slice` method is included.
> Fixed TemplateExpressions

- src/class/Transpiler.ts
- Changed `game.ReplicatedStorage` to `game:GetService("ReplicatedStorage")`
- Changed it so there can't be naming conflicts between transpiler-defined functions and methods or static members
- Made it so metamethods are now 100% inter-operable with Lua and respect inheritance
- Removed hard-coded `toString` cheat
- Made it so expressions in the first argument of for loops transpile to valid Lua code
Update:
- Fixed inheritance model
Update 2:
- Edited it according to the code-quality demands of Osyris
- Made the Transpiler error when a script-kiddie tries to use a return statement within a constructor function
Update 3:
- Fixed issues that the linter pointed out
- Updated the code that checks whether or not a return statement is used in a constructor
> Fix metamethods

- src/class/Transpiler.ts
The old system messed things up:
```ts
abstract class Item {
public static Game: Person = new Person();
public Owner: Person = Item.Game;
public readonly ClassName: string = "Item";
}
class Medkit extends Item {
public readonly ClassName: string = "Medkit";
constructor() {
super();
this.ClassName = "Mine";
}
}
```
```lua
local Item, Medkit;
do
Item = {};
Item.__index = {};
Item.Game = Person.new();
Item.constructor = function(self, ...)
self.Owner = Item.Game;
self.ClassName = "Item";
return self;
end;
end;
do
Medkit = {};
Medkit.__index = setmetatable({}, Item);
Medkit.new = function(...)
return Medkit.constructor(setmetatable({}, Medkit), ...);
end;
Medkit.constructor = function(self)
self.ClassName = "Medkit";
Item.constructor(self);
self.ClassName = "Mine";
return self;
end;
end;
``` …
> Fix precedence in class inheritance

- src/class/Transpiler.ts
This is just a small readability improvement of compiled code. Currently, an accessor table is initialized, and the functions are added separately. This makes it so getters/setters are now initialized inside said table.
Consider this example:
```TypeScript
class Test {
get test() {
return "test"
}
}
```
Previously, it would compile like so:
```Lua
do
Test = {};
Test.__index = {};
Test.new = function(...)
return Test.constructor(setmetatable({}, Test), ...);
end;
Test.constructor = function(self, ...)
return self;
end;
Test._getters = {};
Test._getters.test = function(self)
return "test";
end;
local __index = Test.__index
Test.__index = function(self, index)
local getter = Test._getters[index];
if getter then
return getter(self);
else
return __index[index];
end;
end;
end;
```
Now, it will …
> Initialize Transpiled Accessors In-Line

- src/class/Compiler.ts
- src/class/Transpiler.ts
- src/class/errors/TranspilerError.ts
- src/test.ts
- tests/src/errors/roactNew.spec.tsx
```ts
class RoactCustomComponent extends Roact.Component {
// ...
}
const myComponent = new RoactCustomComponent({});
```
This is not supported by Roact.
Will also give recommended usage in error message as well.
> Transpiler Error on "new RoactComponent(...)"

- src/class/Transpiler.ts
- src/class/errors/TranspilerError.ts
- tests/package.json
- tests/src/roact.spec.tsx
* Tidy up Roact-based code internally
* Type checks improved and not duplicate (now a function - `isRoactElementType`)
* Function expressions that return `Roact.Element[]` or `Roact.Element` better differentiated with `type.isArray()`
* Added proper error types for the other Roact transpiler errors
* Removal of `this.props.children` in favour of `this.props[Roact.Children]` - first one was a hack that would break when an element was reconciled. It's better to just stay consistent with Roact itself.
* Fixed function expressions that returned a `Roact.Element` - Roact_merge would previously merge the element's properties with the other children which would lead to Roact throwing a confusing error.
* Supports using element access expressions that return `Roact.Element[]` to support using …
> Roact refactoring and fixes

- src/class/Transpiler.ts
- src/class/errors/TranspilerError.ts
**Exporting and importing should work normally now.**
- Added support for `export let`
- Made it so variables exported from namespaces are referenced properly
- Made it so `export default` works for class expressions and function literals (and possibly tuples, I don't remember whether that was broken)
- Made it so `export {REFERENCE as NAME};` works properly
- Fixed some bugs where `export = ` would not work as it should.
- Changed the exportStack to a `Set` so that it would not have duplicates in the `_exports` dump. This would occur if a developer defined a namespace twice.
Also added an error if there are multiple `export =` statements.
UPDATE:
- Fixed dynamic import() function calls
- Fixed imports of the form `import "./Source"`
- Fixed bug where variables from another library would …
> Fix exporting and importing

- src/class/Transpiler.ts
I don't know how people even use Roblox-TS without this. 
Allows a user to define a TS library like so
```ts
export = class {};
```
Then import like so
```ts
import Event from "./Event";
```
Relatated to this: https://github.com/roblox-ts/roblox-ts.github.io/pull/12
> Fix importing default exportEquals statements

- src/class/Transpiler.ts
- Make for in statements access proper keys in arrays
- Also makes arrays start indexing at 0 in for in loops.
```ts
const children = [1, 2, 3];
for (const key in children) {
print(children[key]);
}
```
```lua
local children = {1, 2, 3}
for key = 0, #children - 1 do
print(key, children[key + 1])
end
```
```
0	1
1	2
2	3
```
Fixes #181
> Make for in statements access proper keys in arrays

- src/class/Transpiler.ts
- src/class/errors/TranspilerError.ts
**Changes:**
- Variables will now scope to for loops that contain a function definition
- Class expressions are now disallowed as arguments in for statements
- Fixed issues relating to unary expressions as arguments
- Fixed issue with equal statements not being properly detected in the first argument of a for statement.
Fixes #176
> Fix ForStatement bugs

- .prettierignore
- lib/RuntimeLib.lua
- src/transpiler/module.ts
- Make it so the first parameter to `TS.import` is always an object. Previously, we would pass in a string upon which we could call `GetService`, but we now instead do `GetService` in-line.
- Make it so TS.import caches data returned from `require` and checks for circular dependency chains.
> Improve import

- src/transpiler/binding.ts
- tests/src/destructure.spec.ts
An optimization from #200 caused an issue (#221) with varargs.
There may be a better way to implement this optimization, but for now I think it should be reverted.
> Fix for varargs bug

- src/TranspilerState.ts
- src/transpiler/binding.ts
- src/transpiler/class.ts
- src/transpiler/enum.ts
- src/transpiler/function.ts
- src/transpiler/loop.ts
- src/transpiler/namespace.ts
- src/transpiler/variable.ts
Separates variable declaration lists into multiple lines.
Example:
```TS
const a = 1, b = 2;
```
Before:
```Lua
local a, b = 1, 2;
```
After:
```Lua
local a = 1;
local b = 2;
```
This cleans up the code significantly and allows us to optimize certain cases better.
For example, arrow functions / function expressions will now compile like:
```TS
const foo = () => {};
```
```Lua
local foo;
foo = function() end;
```
This allows `foo` to reference itself recursively.
> Refactor variable.ts

- src/transpiler/literal.ts
- tests/src/literal.spec.ts
In TypeScript, you can use underscores in numeric literals for visual purposes. e.g. They can be used as commas to make numbers easier to read.
```ts
const myX = 1_000_000;
```
```lua
local myX = 1000000
```
> Numeric literal fix

- src/transpiler/loop.ts
- src/typeUtilities.ts
- tests/src/tuple.spec.ts
- For loops without a final statement won't cause the transpiler to explode.
- Tuples will be treated as Arrays.
```ts
function returnsTuple(): [number, number, number] {
return [1, 2, 3];
}
const x = returnsTuple();
for (const y of x) {
print(y); // Previously, removing this line would cause a transpiler explosion
}
print(x.pop());
```
Before:
```lua
local returnsTuple = function()
return 1, 2, 3;
end;
local x = { returnsTuple() };
for _, y in pairs(x) do -- Not broken, but not as great either
print(y);
end;
print(x:pop()); -- does not exist, error!
```
After:
```lua
local returnsTuple = function()
return 1, 2, 3;
end;
local x = { returnsTuple() };
for _0 = 1, #x do -- optimized!
local y = x[_0];
print(y);
end;
print(table.remove(x)); -- great!
```
> Tuple array fixes

- src/transpiler/binding.ts
- src/transpiler/identifier.ts
- tests/src/exportLet.spec.ts
Fixes #267 
It took a while to figure out what the issue was, but I got it working now.
For one, `ts.TypeGuards.isObjectBindingPattern(parent)` needed to be added in the indentifier tree-climbing code. This fixed almost every case, but it was still getting some declarations wrong. Consider the following code:
```ts
const plr = {
ClassName: "Player",
Name: "Validark",
};
export let { ClassName: b, Name: c } = plr;
export let { ClassName, Name } = plr;
print(b, c, ClassName, Name);
```
It was transpiling to this:
```lua
local _exports = {};
local plr = {
ClassName = "Player";
Name = "Validark";
};
_exports.b, _exports.c = plr["ClassName"], plr["Name"];
ClassName, Name = plr["ClassName"], plr["Name"]; -- WRONG
print(_exports.b, _exports.c, _exports.ClassName, _exports.Name);
return _exports; …
```
> Export let fix

- src/transpiler/call.ts
- tests/src/array.spec.ts
Pretty straightforward and simple PR:
- add delete macro to Maps (just copy and pasted from Set)
- optimize Push calls when subExp is an Identifier (only takes one check: `if (ts.TypeGuards.isIdentifier(subExp))`). Now spits out `t[#t + 1] = v`
This means this ts will now compile to the following Lua:
```ts
class Noodle {
public strings = new Array<string>();
}
const noodle = new Noodle();
const strings = noodle.strings;
noodle.strings.push("Rigatoni");
strings.push("Spaghetti");
```
Transpiled Lua:
```lua
local Noodle;
do
Noodle = {};
Noodle.__index = {};
Noodle.new = function(...)
return Noodle.constructor(setmetatable({}, Noodle), ...);
end;
Noodle.constructor = function(self, ...)
self.strings = {};
return self;
end;
end;
local noodle = Noodle.new();
local strings = noodle.strings; …
```
> Add delete macro to maps and optimize push macro

- src/transpiler/indexed.ts
- src/transpiler/loop.ts
- tests/src/loop.spec.ts
Previously, we could optimize for loops if they were in the form
```ts
for (let i = 0; i <= 10; i++) {
}
```
The 10 had to be a numeric literal in order to work. Now, the 10 can be an identifier, if it is a number type, and it is a constant. That way, we can be sure the value will not change during the for-loop.
EDIT: Moved small bug fix to separate PR
> Improve for-loop logic

- src/transpiler/call.ts
This affects code in `new.ts` to make it use transpileCallArguments properly. Fixes spacing in new statements
> Fix spacing in new parameters

- src/transpiler/expression.ts
The transpiler will incorrectly error when using `this` inside of a ClassExpression. This PR fixes that.
> ClassExpression hotfix

- src/TranspilerState.ts
This TS code should transpile to the following Lua code:
```ts
export function bar() {}
export function foo() {}
export default foo;
```
```lua
local _exports = {};
local bar = function()
end;
local foo = function()
end;
_exports._default = foo;
_exports.bar = bar;
_exports.foo = foo;
return _exports;
```
Previously, we were getting 2 default values because `(_exports.foo).isDefaultExport()` is true, even if it isn't the particular statement that makes it the default export.
> Default export hotfix

- lib/RuntimeLib.lua
- src/errors/TranspilerError.ts
- src/transpiler/call.ts
- src/transpiler/expression.ts
- src/transpiler/loop.ts
- src/transpiler/new.ts
- tests/src/array.spec.ts
- tests/src/map.spec.ts
- tests/src/object.spec.ts
- tests/src/set.spec.ts
All of these changes are in regards to the macro functionality. This pull request makes outputted code more consistent, more optimized, and less prone to bugs.
Fixes:
- Fixed occasions where invalid Lua code would be outputted. Now we make sure to wrap table literals in parenthesis when writing or reading from them using `[]` and we make sure to put unused expressions after a `local _ = `. One should note that this fixes a number of potential problems.
```ts
if (new Set<number>().has(1)) print("It has 1!");
```
What this used to compile to:
```lua
-- invalid Lua
if ({}[1] ~= nil) then
print("It has 1!");
end;
```
What this compiles to now:
```lua
-- Valid!
if (({})[1] == true) then
print("It has 1!");
end;
```
- Fixes map_set/set_add chains being used together with array literal …
> Macro rework

- lib/RuntimeLib.lua
- src/transpiler/call.ts
- tests/src/string.spec.ts
- Make our string.split implementation match the output of Roblox's and JavaScript's split functions (our previous version failed a lot of the test cases I added)
- Add a second parameter, `plain`, to `string.split`. This is modeled after the third parameter of `string.find`. 
- Add string.split macro for an empty string separator or when the plain parameter is set to true
- Add a bunch of test cases
After merging, please put this in rbx-types:
```ts
/** Returns an array of substrings, separated by each `sep`.
* Accepts Lua character classes, unless `plain` is true.
*/
split(sep: string, plain?: boolean): Array<string>;
```
Requires merging this:
https://github.com/roblox-ts/rbx-types/pull/59
> Update string.split implementation

- src/transpiler/new.ts
I overlooked this edge case.
```ts
const set = new Set([...[1, 2, 5], 9, ...[0]]);
const set2 = new Set([...[1, 2, 5].concat([1])]);
```
Old:
```lua
local set = {
[unpack({ 1, 2, 5 })] = true;
[9] = true;
[unpack({ 0 })] = true;
};
local set2 = {
[unpack(TS.array_concat({ 1, 2, 5 }, { 1 }))] = true;
};
```
New:
```lua
local set = TS.set_new(TS.array_concat({ 1, 2, 5 }, { 9 }, { 0 }));
local set2 = TS.set_new(TS.array_concat(TS.array_concat({ 1, 2, 5 }, { 1 })));
```
> Fix spread expressions inside set/map constructors

- src/errors/TranspilerError.ts
- src/transpiler/new.ts
Problem:
```ts
const foo = new Map([[, "Decay"]]);
```
```ts
local foo = {
[nil] = "Decay"; //error
};
```
> Disallow nil indexing in maps/sets

- lib/RuntimeLib.lua
- src/transpiler/binary.ts
- src/transpiler/unary.ts
- tests/src/bitwise.spec.ts
- Adds support for the bitwise NOT operator (`~`)
- Yields one's complement (inverted value) of `a`
a | NOT a
-- | ----------
0 | 1
1 | 0
Small demo:
```typescript
let a = 0xFE; // decimal: 254
let b = ~a; // -0xFF (decimal: -255)
b &= 0xFF; // 0x01 (decimal: 1)
```
```typescript
let a = 0b01; // 1
let b = ~a & 0b11; // 2
```
Works towards #156
> Add bitwise NOT, logical right shift operators.

- src/compiler/expression.ts
- src/compiler/yield.ts
- src/errors/CompilerError.ts
This PR allows the following code to work:
```TS
function *getDescendants(instance: Instance): IterableIterator<Instance> {
for (const child of instance.GetChildren()) {
yield child;
yield* getDescendants(child);
}
}
for (const descendant of getDescendants(game)) {
print(descendant.GetFullName());
}
```
However, I have some concerns about things like `const x = yield 1;`.
TS seems to indicate that `x` is of type `any` here.
Should we error if it's used like this? Is there a valid workflow that involves this?
> Add support for yield*

- lib/RuntimeLib.lua
- src/CompilerState.ts
- src/compiler/binary.ts
- src/compiler/binding.ts
- src/compiler/call.ts
- src/compiler/class.ts
- src/compiler/conditional.ts
- src/compiler/indexed.ts
- src/compiler/spread.ts
- src/compiler/variable.ts
- src/typeUtilities.ts
Made a few changes to the runtime library:
- Made `array_push_apply` accept any number of subsequent tables, to reduce the number of necessary middle-steps
- Made `array_push_apply` and `array_copy` used internally (by `array_concat` and `array_sort` respectively)
- Made `set_new`/`map_new` iterate numerically
Made a number of changes to the IIFE implementation:
- Fixed cases where a computed property index would be computed multiple times, especially if it involves a function call. In my defense, this was broken before PR #340 .
```ts
const arr = [1, 2, 3, 4, 5];
function f() {
return 0;
}
// previously, this could call f() twice
arr[f()] *= 2;
```
- Optimized `array_push` to no longer need to call `array_concat` internally anymore on spreadable indexes.
- Made some adjustments to how …
> Remove IIFE stability upgrade

- tests/src/literal.spec.ts
Credit to @grubsteak from https://github.com/roblox-ts/roblox-ts/pull/344/files#diff-ef2fc1aa5b9776f69d228a3b40c4ca47L12
> compare numbers instead of strings in literal tests

- src/compiler/loop.ts
```ts
const o = { a: 1 };
// try changing this to Object.keys and Object.entries
for (const i of Object.values(o)) {
print(i);
}
```
Implementation notes: We already had code to deal with `Object.entries`, which is just the Map logic. The only code I added is the code that checks if it is `Object.keys/entries/values` and I also added the logic for `Object.values` (1-2 lines). The `isArray` and `isString` blocks are unchanged, they were simply moved so that the `isExpMapType | isExpSetType | isExpValuesType` logic would come first.
> [READY TO MERGE] Optimize Object.values/entries/keys in forOf loops

- src/compiler/expression.ts
- src/compiler/index.ts
- src/compiler/literal.ts
- src/compiler/template.ts
- src/test.ts
- tests/package-lock.json
- tests/package.json
- tests/src/global.d.ts
- tests/src/literal.spec.ts
- tests/src/roact.spec.tsx
- tests/src/string.spec.ts
- tests/src/template.spec.ts
Fixes #166
This now works:
```TS
const OPERATIONS: { [index: string]: (a: Vector3, b: Vector3) => Vector3 } = {
"*": (a, b) => a.mul(b),
"/": (a, b) => a.div(b),
"+": (a, b) => a.add(b),
"-": (a, b) => a.sub(b)
};
function m(strings: TemplateStringsArray, ...operands: Vector3[]): Vector3 {
const operators = strings.map(v => v.trim());
let value = operands.shift()!;
operators.shift();
for (let i = 0; i < operands.length; i++) {
const operator = operators[i].trim();
if (operator in OPERATIONS) {
const operation = OPERATIONS[operator];
value = operation(value, operands[i]);
}
}
return value;
}
const a = new Vector3(1, 2, 3);
const b = new Vector3(4, 5, 6);
const pos = m`${a} * ${b} - ${new Vector3(1, 2, 3)}`;
print(pos.X, pos.Y, pos.Z); // 3    8    15
```
Requires the following type …
> Add support for TaggedTemplateExpression

- src/compiler/call.ts
- Adds logic for `isClassName` macro.
I would prefer if we settled on one of these pairs. I prefer the second.
|type|ClassName|
|:-:|:-:|
|typeIs|classNameIs|
|isType|isClassName|
- Adds logic for `isClass` macro (formerly `isClassName`)
Types: https://github.com/roblox-ts/rbx-types/pull/80
> add isClass macro to compiler

- src/compiler/indexed.ts
- tests/src/binary.spec.ts
Instead of specifying which Operands we should push, we should specify which operand types we know we don't need to push. When in doubt, it should push to a variable to make sure we don't output incorrect code.
> Move to explicitly specifying which expressions shouldn't be pushed in getWritableOperandName

- lib/RuntimeLib.lua
- src/compiler/call.ts
- tests/src/array.spec.ts
Fixes cases like this:
```ts
let arr = [0];
arr.push(1, 2, arr[1]); // arr[1] should be undefined
```
> Simplify push implementation

- src/CompilerState.ts
- src/Project.ts
- src/compiler/binary.ts
- src/compiler/call.ts
- src/compiler/function.ts
- src/compiler/indexed.ts
- src/compiler/new.ts
- src/compiler/object.ts
- src/compiler/security.ts
- src/errors/CompilerError.ts
- src/test.ts
- src/typeUtilities.ts
- tests/src/binary.spec.ts
- tests/src/errors/funcExpMethodCall.spec.ts
- tests/src/object.spec.ts
After this PR is merged, I consider roblox-ts to officially support objects.
This PR fixes the following issues:
Fixes https://github.com/roblox-ts/roblox-ts/issues/351
https://github.com/microsoft/TypeScript/issues/31469
This PR fully finishes the last thing I considered necessary to close this issue:
Fixes https://github.com/roblox-ts/roblox-ts/issues/131
Also:
- The following code should error now:
```ts
const o = {
c: 1,
a: function add(i: number): number {
if (i === 0) {
return 0;
} else {
return i + add(i - 1); // footgun! `this` won't get passed into add!
}
},
};
```
- Minor fixes for the following:
- Fixes whitespace issues with Set/Map instantiation, and allows map constructor to be more flexible.
- Fixes https://github.com/roblox-ts/roblox-ts/issues/433
- Fixes …
> Object redux

- src/compiler/new.ts
- src/compiler/object.ts
- tests/package-lock.json
- tests/package.json
- tests/src/object.spec.ts
- tests/src/set.spec.ts
- Fixes WeakMap/WeakSet constructors so that they actually include `setmetatable({}, {__mode = "k"})` and so they do not create invalid expressionStatements in Lua (`appendDeclarationIfMissing`)
- Compiles `TS.Object_assign` in-line in object spread logic, and consolidates it into a single function for the compiler.
- Adds more tests for object spread logic appearing in different places (expected answers came from running the code as JS in Chrome)
Note: parameter [target](https://github.com/roblox-ts/roblox-ts/blob/f64d727314adc441203723b3a4b4484a8a5bc13a/src/compiler/object.ts#L7) is already a readable value, since Objects/Maps/Sets are by default pushed to `_0 = {}`, and are only named from the beginning in-line if they are the target of an identifier setter ([logic …
> Object Redux Addendum

- src/CompilerState.ts
- src/compiler/new.ts
- tests/src/set.spec.ts
I documented they should always be pushed [here](https://github.com/roblox-ts/roblox-ts/blob/master/src/compiler/indexed.ts#L95). This makes sure they always are.
> Make sure Sets/Map Constructors are always pushed

- src/compiler/call.ts
- src/compiler/class.ts
- tests/src/class.spec.ts
Wrapping is redundant because we already have this: https://github.com/roblox-ts/roblox-ts/pull/477/files#diff-50cd0512e4a61af2b2be7f3990caca7fR1024
> Don't wrap ReadableExpressionNames

- src/compiler/indexed.ts
In the future, I may write some code to detect whether a variable is modified within a given space, but for now, this will help cases like these compile better:
```ts
function catchLetters(...letterPairs: Array<LuaTuple<Array<string>>>) {
let i = 96;
for (const [a, b] of letterPairs) {
print(a, string.char(++i));
print(b, string.char(++i));
}
}
```
Before:
```lua
local function catchLetters(...)
local letterPairs = { ... };
local i = 96;
for _1 = 1, #letterPairs do
local _0 = letterPairs[_1];
local a, b = _0[1], _0[2];
local _3 = a;
local _2 = string;
i = i + 1;
print(_3, _2.char(i));
local _5 = b;
local _4 = string;
i = i + 1;
print(_5, _4.char(i));
end;
end;
```
After:
```lua
local function catchLetters(...)
local letterPairs = { ... };
local i = 96;
for _1 = 1, #letterPairs do
local _0 …
```
> Make definedInConst logic a bit smarter

- src/compiler/class.ts
Since we already compile concats of classes with `tostring()`, it is unnecessary and cluttering to have __concat metamethods generated without reason.
> Remove __concat metamethod generation

- src/compiler/class.ts
We need to block a static toString because of the way we now compile classes within a single namespace
> Block static toString

- src/compiler/indexed.ts
- src/typeUtilities.ts
- tests/src/object.spec.ts
Fixes cases like this from calling `f` twice due to not pushing it for a writable value:
```ts
const f = () => 2;
const o: { [i: number]: number } = {
0: 2,
1: 4,
2: 5,
3: 6,
4: 5,
};
const x = o[f()]++;
```
> Fix getWritableOperandName

- src/Watcher.ts
- src/compiler/binary.ts
- src/compiler/binding.ts
- src/compiler/forOf.ts
- src/compiler/function.ts
- src/compiler/spread.ts
- src/compiler/variable.ts
- src/errors/CompilerError.ts
- src/typeUtilities.ts
- tests/src/destructure.spec.ts
Still need to add tests. i.e.:
```TS
const obj = {
y: [new Map([["a", 1]])]
};
let d: string;
let e: number;
({
y: [[[d, e]]]
} = obj);
print(d, e); // a 1
```
> Improve destructured assignment type tracking

- src/CompilerState.ts
- src/compiler/module.ts
- src/compiler/security.ts
- src/compiler/sourceFile.ts
- tests/src/errors/reservedId.spec.ts
"_exports" -> "exports"
"_default" -> "default"
These are already reserved keywords in TS, so we're safe. Magically resolves a few bugs.
Slightly breaking change, these packages would need to be recompiled:
https://www.npmjs.com/package/@rbxts/tween @Validark 
https://www.npmjs.com/package/@rbxts/yield-for-character @Validark 
https://www.npmjs.com/package/@rbxts/net @Vorlias
> Rename _exports/_default to exports/default

- CHANGELOG.md
- src/CompilerState.ts
- src/Project.ts
- src/cli.ts
- src/compiler/binary.ts
- src/compiler/call.ts
- src/compiler/conditional.ts
- src/compiler/indexed.ts
- src/compiler/object.ts
- src/compiler/spread.ts
- src/compiler/truthiness.ts
- src/compiler/unary.ts
- Removed precedingStatement reuseable Id architecture.
- While hypothetically useful, it doesn't really have much of an impact on real code. There's no real use case for being able to intelligently condense both `i`s in `print(++i, i++)` to the same temporary variable.
- Added `--logTruthyChanges` compiler option
- Removed the functionality of pushPrecedingStatementToNewId which can return the passed in value if it matches `_\d+`. As the precedingStatement system is being used more, this becomes less safe the more we have scenarios where temporary values can have their value changed. We will hopefully have another truthy PR which involves reusing and reassigning temp variables a lot, so this will become unsafe moving forward.
- This should be replaced with a sound system which only …
> Truthy update

- src/compiler/module.ts
Previously this code was producing the wrong import statements:
```ts
import { CharacterRigR15 } from "@rbxts/yield-for-character";
import { validateTree } from "@rbxts/validate-tree";
function onCharacterAdded(char: CharacterRigR15) {
const t1 = tick();
validateTree(char, CharacterRigR15);
print(tick() - t1);
}
```
Lua:
```diff
local TS = require(game:GetService("ReplicatedStorage"):WaitForChild("rbxts"):WaitForChild("RuntimeLib"));
local CharacterRigR15 = TS.import(TS.getModule("yield-for-character")).CharacterRigR15;
- local validateTree = TS.import(TS.getModule("yield-for-character")).validateTree;
local function onCharacterAdded(char)
local t1 = tick();
validateTree(char, CharacterRigR15);
print(tick() - t1);
end;
```
For some reason, when one mouses-over the validate-tree import, it …
> Fix importing when there is a version mismatch

- lib/RuntimeLib.lua
I (accidentally) ran into this with my `@rbxts/yield-for-tree@1.0.6` package.
My package.json had this in it:
```js
"dependencies": {
"@rbxts/validate-tree": "1.0.0" // note how there is no "^" at the start
}
```
In my project, I had installed `@rbxts/validate-tree@1.0.2`, so it (accidentally) installed like so:
> Respect packages requiring a specific version other than the installed one

- src/compiler/binary.ts
- tests/src/binary.spec.ts
Fixes cases like these:
```ts
let x = 5;
// prettier-ignore
(x) *= 9;
```
> Fix parenthesized left-hand side on equals expressions

- lib/RuntimeLib.lua
- src/compiler/forOf.ts
- src/compiler/spread.ts
- tests/src/string.spec.ts
- Adds `TS.string_spread` function which properly destructures unicode graphemes (without regarding clusters, like utf8.graphemes does). This is used for destructuring strings now.
- This will make string iteration and string destructuring out of the box more useful for working with graphemes, and also is more in line with how JS works.
Inspired by https://stackoverflow.com/questions/4547609/how-do-you-get-a-string-to-a-character-array-in-javascript/34717402#34717402
> Make string destructuring and iterating unicode safe

- CHANGELOG.md
- src/compiler/binary.ts
- src/compiler/call.ts
- src/compiler/class.ts
- src/compiler/expression.ts
- src/compiler/function.ts
- src/compiler/object.ts
- src/errors/CompilerError.ts
- src/test.ts
- src/utility/type.ts
- tests/src/errors/method-callback/conflictingClassMethods.spec.ts
- tests/src/errors/method-callback/conflictingDefinitions.spec.ts
- tests/src/errors/method-callback/conflictingObjectMethodSet.spec.ts
- tests/src/errors/method-callback/conflictingVars.spec.ts
- tests/src/object.spec.ts
- Unified logic for isMethodDeclaration and isDefinedAsMethod
- Removed the `:` and `.` magic string manipulation. It doesn't make sense with our new isMethodDeclaration/isDefinedAsMethod system
- Fixed the regressions introduced in https://github.com/roblox-ts/roblox-ts/pull/646
- There was a problem that arose from `isParameteredNode` functions not always being handled in `isMethodDeclaration`
- There was a problem with `self` not getting inserted in some methods
> Method Redux

- src/compiler/forOf.ts
- src/utility/general.ts
> Update skipNodes logic

- CHANGELOG.md
- lib/RuntimeLib.lua
- tests/src/array.spec.ts
- Simplify `array_flat_helper` a little
- Removed limited support for arrays with holes. We should just release a separate library for that. Previously, we partially copied JS' behavior on empty values in arrays. However, developers should expect that their callbacks will run on every value of an array.
- Fixed `Array.reduce` and `Array.reduceRight` functions
- They now pass in the right index into the reducer function (arrays start at 0, not 1)
- They now pass the array into the reducer function
- They now error when attempting to reduce an empty array without an initialValue passed in
- `undefined` is now a valid initialValue
- Removed limited support for array methods with holes. We don't support arrays with holes in them.
- If want to strip an array of `nil` values, use …
> Fix reducers, remove nullable array ambiguity

- src/compiler/roact.ts
- tests/src/roact.spec.tsx
Fixes expressions where the identifier is a `Roact.Element[]`. 
This previously worked (lol) but was changed when I fixed issues with other identifier expressions working when they shouldn't.
Test also added to ensure this works now.
> Fix Roact.Element[] expression regression

- lib/RuntimeLib.lua
This is the problem Vorlias was having: There was a circular dependency and our code which checks against that didn't work because `loadedLibraries[module] = true` made it skip the dependency check logic, even if the library hadn't finished loading.
> Fix circular dependency checker

- CHANGELOG.md
- src/compiler/enum.ts
- src/errors/CompilerError.ts
- src/test.ts
- tests/src/errors/noEnumMerging.spec.ts
This PR bans enum merging to simplify compilation. It's also a bit of a footgun since you really should only ever have one source of truth for data like that.
```TS
enum GameState {
None,
Lobby,
InProgress,
End,
}
```
```Lua
local GameState;
do
local _0 = {};
GameState = setmetatable({}, { __index = _0 });
GameState.None = 0;
_0[0] = "None";
GameState.Lobby = 1;
_0[1] = "Lobby";
GameState.InProgress = 2;
_0[2] = "InProgress";
GameState.End = 3;
_0[3] = "End";
end;
```
This new format allows you to iterate over enum keys and values using the following:
```TS
Object.keys(GameState); // "None" | "Lobby" | "InProgress" | "End"
Object.values(GameState): // GameState
```
while still allowing inverse lookups for debugging:
```TS
declare const myState: GameState;
print(GameState[myState]);
```
> Disallow enum merging

- lib/RuntimeLib.lua
- tests/src/array.spec.ts
Adds `mapFiltered` method to arrays, which works like the `map` function but excludes undefined values.
I think `mapFiltered` is the best name because it is more indicative of "map with exceptions" than "filter but it maps", which makes less sense. In intellisense, it will be right underneath `map`, and should seem to be a clear alternative to using `array.map`.
Ripped definition from Cryo. I just modified the callback arguments to match our spec. `i` -> `i - 1`, and added the `list` argument as well.
Closes https://github.com/roblox-ts/roblox-ts/issues/716
> Add mapFiltered

- lib/RuntimeLib.lua
Use cases:
- Sometimes circular references are necessary, for example, `parent` -> `child` -> `parent` situations
Fixes:
- Make it so recursive objects can be properly cloned
Changes:
- Allows keys of type "table" to get deepCopied as well.
- Bad practice, but imo anything returned by deepCopy should always be completely divorced from the original object tree
Question: Should we handle metatables, and if so, how? We could optionally add something like this:
```lua
local mt = getmetatable(object)
if type(mt) == "table" then
setmetatable(result, mt)
end
```
> Update Object.deepCopy to not crash on recursive objects

- package-lock.json
- src/compiler/call.ts
- src/compiler/new.ts
- tests/spec.lua
Changes
=======
Now using `table.create` as it functionally does the exact same thing. Also added the second argument (value) of table.create to the array constructor.
Removes the limitation of only being able to use integer literals as an argument to the array constructor.
Now uses `table.find`.
Now added.
Fixes #598
> Array and string improvements

- lib/RuntimeLib.lua
- src/compiler/function.ts
- src/compiler/yield.ts
- Move Generator logic into `TS.generator` function
- This should make declaring Generators shorter, and should also allow full support of returning from generators :)
- Make yield a simple coroutine.yield call.
Fixes https://github.com/roblox-ts/roblox-ts/issues/556
> Improve Generators

- src/compiler/truthiness.ts
I think it is best to always check for Lua truthiness in truthy checks, since there are some cases where a variable could be undefined but the type system does not recognize it:
```ts
const [a] = new Array<string>(); // a is typed as a `string` when it should be `string | undefined`
if (a) { // should we only check if a ~= ""?  No, we should check `a ~= "" and a`
}
```
> Always check Lua truthiness

- package.json
This is good practice, [as stated by NPM](https://docs.npmjs.com/misc/scripts). Currently, if using roblox-ts from the github repo 
{"roblox-ts": "git://github.com/roblox-ts/roblox-ts.git#master"}
then the `out` directory will not exist, and the install will fail.
To fix this, `prepare` will run tsc when installing the library from github.
Another solution would be to keep the `out` directory on github.
> Change build from "prepublishOnly" to "prepare"

- src/compiler/call.ts
Temporarily disallows:
```ts
declare function foo(): void;
foo?.();
```
> Disallow func?.()

- src/Project.ts
This change just adds an extra check to `Project.copyFiles()` so that symbolic links are explicitly **NOT** overwritten.
When copying files after compiling, roblox-ts will overwrite everything. This is usually not a problem. However, when crossing on symlinks, the situation becomes complicated:
```
Starting initial compile..
[Error: EPERM: operation not permitted, symlink 'C:\Users\davness\Documents\Git\roblox-ts-skeleton\Places\global\src' -> 'C:\Users\davness\Documents\Git\roblox-ts-skeleton\Places\test1\lua\global'] {
errno: -4048,
code: 'EPERM',
syscall: 'symlink',
path: 'C:\\Users\\davness\\Documents\\Git\\roblox-ts-skeleton\\Places\\global\\src',
dest: 'C:\\Users\\davness\\Documents\\Git\\roblox-ts-skeleton\\Places\\test1\\lua\\global'
}
```
If we run the command again:
```
Running …
```
> Do not overwrite symbolic links

- src/Project.ts
Fixes #934
When copying a directory from `rootDir` to `outDir`, all files except the ones the compiler tags as to-be-compiled will be copied over.
> Don't copy files that should be compiled over to out dir

- .github/workflows/ci.yml
because of the `prepare` script in package.json, it already builds the compiler using the npm install action.
> Remove duplicate CI build

- src/LuaRenderer/RenderState.ts
- src/LuaRenderer/nodes/expressions/renderFunctionExpression.ts
- src/LuaRenderer/nodes/expressions/renderMap.ts
- src/LuaRenderer/nodes/expressions/renderMixedTable.ts
- src/LuaRenderer/nodes/expressions/renderSet.ts
- src/LuaRenderer/nodes/expressions/renderUnaryExpression.ts
- src/LuaRenderer/nodes/statements/renderAssignment.ts
- src/LuaRenderer/nodes/statements/renderBreakStatement.ts
- src/LuaRenderer/nodes/statements/renderCallStatement.ts
- src/LuaRenderer/nodes/statements/renderComment.ts
- src/LuaRenderer/nodes/statements/renderContinueStatement.ts
- src/LuaRenderer/nodes/statements/renderDoStatement.ts
- src/LuaRenderer/nodes/statements/renderForStatement.ts
- src/LuaRenderer/nodes/statements/renderFunctionDeclaration.ts
- src/LuaRenderer/nodes/statements/renderIfStatement.ts
- src/LuaRenderer/nodes/statements/renderMethodDeclaration.ts
- src/LuaRenderer/nodes/statements/renderNumericForStatement.ts
- src/LuaRenderer/nodes/statements/renderRepeatStatement.ts
- src/LuaRenderer/nodes/statements/renderReturnStatement.ts
- src/LuaRenderer/nodes/statements/renderVariableDeclaration.ts
- src/LuaRenderer/nodes/statements/renderWhileStatement.ts
Indents made more centralised. Only touched inside RenderState.
Semicolons (determined by util/getEnding) also only used in one place.
> Add RenderState.line(), adds indent, semis and "\n" automatically.

- src/TSTransformer/README.md
- src/TSTransformer/macros/propertyCallMacros.ts
Also removed classname property in every and some, not used since automated comments were added.
Credits to @Dog2puppy for the base implementation.
> Add macros for object.entries, keys and values

- src/LuaAST/impl/globals.ts
- src/TSTransformer/README.md
- src/TSTransformer/macros/propertyCallMacros.ts
```ts
let arr = [4, 5, 6, 7];
let b = arr.indexOf(2) * 2;
let c = arr.lastIndexOf(5);
let d = arr.lastIndexOf(5, 1);
```
```lua
local arr = { 4, 5, 6, 7 }
local b = ((table.find(arr, 2) or 0) - 1) * 2
-- ▼ ReadonlyArray.lastIndexOf ▼
local _0 = -1
for _1 = #arr, 1, -1 do
if arr[_1] == 5 then
_0 = _1 - 1
break
end
end
-- ▲ ReadonlyArray.lastIndexOf ▲
local c = _0
-- ▼ ReadonlyArray.lastIndexOf ▼
local _1 = -1
for _2 = 2, 1, -1 do
if arr[_2] == 5 then
_1 = _2 - 1
break
end
end
-- ▲ ReadonlyArray.lastIndexOf ▲
local d = _1
```
> Add `ReadonlyArray.indexOf()` and `ReadonlyArray.lastIndexOf()`

- src/LuaAST/types/nodes.d.ts
- src/TSTransformer/macros/constructorMacros.ts
added a type generic to lua.Array, defaults to lua.Expression which creates same behaviour as before.
`lua.id("value")` may conflict with already scoped variables, better to use a tempid.
> Simplify map constructor macro

- src/TSTransformer/nodes/expressions/transformConditionalExpression.ts
- src/TSTransformer/util/types.ts
makes it use "condition and trueValue or falseValue", where available. Needs implementation of `canBeFalsy`, but I'm not familiar with types.
> [draft] simplify conditionalExpression

- src/CLI/commands/build.ts
- src/Project/Project.ts
- src/Shared/fsUtil.ts
Cleans out any files or folders that don't have a matching file/folder in `rootDir`. 
Basic working implementation, subject to change.
> Implement FS orphan file cleanup

- package-lock.json
- package.json
- src/Project/Project.ts
- src/TSTransformer/classes/MacroManager.ts
Uses `ts.createEmitAndSemanticDiagnosticsBuilderProgram` + `ts.readBuilderProgram` to add support for incremental builds.
Will compile any files that change + any files that reference changed files (necessary for type-based emit + things like const enums).
> Incremental Build Support

- src/TSTransformer/classes/TransformState.ts
- src/TSTransformer/macros/propertyCallMacros.ts
consider this snippet
```lua
local _1
if _0 ~= nil then
_1 = true
else
_1 = false
end
```
This was previously quite tedious, having to implement it like this.
```ts
const returnId = lua.tempId();
lua.list.push(statements, lua.create(lua.SyntaxKind.VariableDeclaration, {
left: returnId,
right: undefined,
}));
```
Now it is as simple as
```ts
const returnId = state.pushToVar(undefined);
```
> Make state.pushToVar() also initialise without value

- src/Shared/diagnostics.ts
- src/TSTransformer/README.md
- src/TSTransformer/nodes/expressions/transformExpression.ts
- src/TSTransformer/nodes/expressions/transformVoidExpression.ts
Support [void expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void) (to increase coverage over the TS language).
Example usage:
```ts
arr.forEach(val => f(val));      // (1)  the return values of `f(val)` are propagated (
arr.forEach(val => { f(val); }); // (2)  okay
arr.forEach(val => void f(val)); // (3)  okay
```
> Support void expressions

- src/LuauAST/impl/globals.ts
- src/TSTransformer/README.md
- src/TSTransformer/macros/propertyCallMacros.ts
Replicates native node.js behaviour (types do that too)
`print("abc".includes("%b", 2))` will compile to
```lua
print(string.find(string.sub("abc", 3), string.gsub("%b", "%^%$%(%)%%%.%[%]%*%+%-%?", function(_0)
return "%" .. _0
end)) ~= nil)
```
`string.sub("abc", 3)` is offset 1 of the second argument, which is "indexFrom". As usual, JS is 0-based, lua is 1-based.
```
string.gsub("%b", "%^%$%(%)%%%.%[%]%*%+%-%?", function(_0)
return "%" .. _0
end))
```
This is a little bit of magic, what it does is prefix all the magic characters in the substring with `%` to escape them, so they're treated as the literal characters.
Then `string.find(...) ~= nil` checks if any match was found.
> add string.includes macro

- src/TSTransformer/nodes/class/transformClassLikeDeclaration.ts
If a class is abstract, then the boilerplate should not generate a `new` method.
> Alternative boilerplate with abstract classes

- src/LuauRenderer/nodes/expressions/renderBinaryExpression.ts
- src/LuauRenderer/nodes/expressions/renderUnaryExpression.ts
- src/LuauRenderer/util/needsParentheses.ts
- src/TSTransformer/macros/propertyCallMacros.ts
Adds parentheses when needed to avoid operator precedence bugs.
```TS
print([1, 2].size() ** 3);
print(`abc: ${undefined || "a"}`);
```
```Lua
print(#({ 1, 2 }) ^ 3)
print("abc: " .. nil or "a")
```
```Lua
print((#({ 1, 2 })) ^ 3)
print("abc: " .. (nil or "a"))
```
Fixes #1095
> Fix operator precedence bugs

- src/TSTransformer/nodes/expressions/transformDeleteExpression.ts
- src/TSTransformer/nodes/expressions/transformElementAccessExpression.ts
- src/TSTransformer/nodes/expressions/transformExpression.ts
- src/TSTransformer/nodes/expressions/transformPropertyAccessExpression.ts
```TS
declare const obj1: { a: { b?: number } };
declare const obj2: { a?: { b?: number } };
```
```Lua
-- delete obj1.a.b;
obj1.a.b = nil
-- print(delete obj1.a.b);
obj1.a.b = nil
print(true)
-- delete obj1["a"]["b"];
obj1.a.b = nil
-- print(delete obj1["a"]["b"]);
obj1.a.b = nil
print(true)
-- delete obj2.a?.b;
local _0 = obj2.a
if _0 ~= nil then
_0.b = nil
end
-- print(delete obj2.a?.b);
local _1 = obj2.a
if _1 ~= nil then
_1.b = nil
_1 = true
end
print(_1)
-- delete obj2["a"]?.["b"];
local _2 = obj2.a
if _2 ~= nil then
_2.b = nil
end
-- print(delete obj2["a"]?.["b"]);
local _3 = obj2.a
if _3 ~= nil then
_3.b = nil
_3 = true
end
print(_3)
```
> Add support for ts.DeleteExpression

- src/CLI/commands/build.ts
- src/CLI/commands/init.ts
- src/CLI/test.ts
- src/Project/classes/VirtualProject.ts
- src/Project/functions/compileFiles.ts
- src/Project/functions/copyFiles.ts
- src/Project/functions/copyItem.ts
- src/Project/functions/createProjectData.ts
- src/Project/functions/setupProjectWatchProgram.ts
- src/Project/types.d.ts
This fix resolves the issue with Rojo crashing on MacOS from being overloaded with too many file changes
> Write only changed

- src/Shared/diagnostics.ts
- src/Shared/util/isValidLuauIdentifier.ts
Adds a diagnostic when the user creates a variable in the form of `_N`, for example
```ts
for (let _0 = 0; 1 > _0; _0++) {}
```
which leads to invalid output and unexpected behaviour, in this case the `for` loop never ending.
```lua
do
local _0 = 0
while 1 > _0 do
local _0 = _0
_0 = _0
_0 += 1
end
end
```
> Check temp id name for normal identifier

- src/TSTransformer/nodes/statements/transformForOfStatement.ts
- tests/src/tests/loop.spec.ts
Fixes iterating over iterable functions when assigning the output tuple to a variable like this:
```ts
for (const tuple of pairs({})) {
print(tuple[0], tuple[1])
}
```
> Fix iterating over an IterableFunction without destructuring + tests

- src/TSTransformer/nodes/transformSourceFile.ts
```ts
export * as foo from "@rbxts/services";
```
incorrectly compiles to
```ts
exports.foo = TS.import(script, TS.getModule(script, "services"))
exports.foo = foo
```
> Fix export * as

- src/Shared/diagnostics.ts
- src/TSTransformer/classes/TransformState.ts
- src/TSTransformer/util/createImportExpression.ts
An attempt to solve part of #1293. Changes the 'noRojoData' diagnostic message to include the path of the expected output file that could be not be found in the Rojo project.
**Before**
**After**
In order to achieve this, I refactored part of the diagnostic system to support passing additional "context" values to DiagnosticFactory functions.
> Add contextual info to the 'noRojoData' diagnostic

- lib/RuntimeLib.lua
- src/Project/functions/compileFiles.ts
- src/Project/functions/createNodeModulesPathMapping.ts
- src/Project/functions/createProjectData.ts
- src/Project/functions/validateCompilerOptions.ts
- src/Shared/diagnostics.ts
- src/TSTransformer/classes/RoactSymbolManager.ts
- src/TSTransformer/util/createImportExpression.ts
supports custom npm scopes as long as:
1. under typeRoots (node_modules/@scope)
2. the scope's path is under the node_modules using the scope's name in Rojo
e.g 
```json
"node_modules": {
"$path": "node_modules/@rbxts",
"@globglogabgalab": {
"$path": "node_modules/@globglogabgalab"
}
}
```
> Support alternative npm scopes

- src/CLI/commands/init.ts
This will give a friendly notice if git init fails:
I was considering using lookpath for this, but I wanted to keep the footprint of this as low as possible so this is just using a catch statement instead.
> Friendly notice if git init fails

- .github/workflows/ci.yml
- .github/workflows/publish.yml
The workflows now use the faster `npm ci` instead of the `npm install` for installing packages.
> Use npm ci instead of npm install

- src/TSTransformer/macros/propertyCallMacros.ts
`print(["a", "b"].join("+"));` would previously include a redundant `if _concat == nil then _concat = " ," end`. With this PR, it will not include the if statement if the provided parameter is a simple primitive.
> Remove redundant if statement for macro arguments that are literals

- src/TSTransformer/util/validateMethodAssignment.ts
Method assign validation would incorrectly compare non-functions with functions
https://roblox-ts.com/playground/#code/GYVwdgxgLglg9mABDMAHAFFAhgawKYBciA3ogM4wBee6AlEQG5wwAmiAvogD4nlWGIwIALYAjPACcOtEuwBQclBlIVqRAIwBWaUA
> Do not compare non-functions in method assignment validation

- src/TSTransformer/macros/callMacros.ts
- src/TSTransformer/nodes/expressions/transformConditionalExpression.ts
- src/TSTransformer/nodes/expressions/transformUnaryExpression.ts
- src/TSTransformer/nodes/statements/transformDoStatement.ts
- src/TSTransformer/nodes/statements/transformForStatement.ts
- src/TSTransformer/nodes/statements/transformIfStatement.ts
- src/TSTransformer/nodes/statements/transformWhileStatement.ts
- src/TSTransformer/nodes/transformLogical.ts
- src/TSTransformer/nodes/transformLogicalOrCoalescingAssignmentExpression.ts
- src/TSTransformer/util/createTruthinessChecks.ts
This argument is only ever provided by `state.getType(node)`
Since this method caches results, there is no performance benefit
Instead, createTruthinessChecks can call `state.getType(node)` directly
Passing anything other than `node`'s type does not make sense, since `node` is used for reporting the truthiness check warning
> Remove duplicate types to createTruthinessChecks

- src/LuauAST/impl/typeGuards.ts
- src/LuauAST/types/nodes.ts
- src/LuauRenderer/nodes/expressions/renderIfExpression.ts
- src/LuauRenderer/util/needsParentheses.ts
- tests/src/tests/ternary.spec.ts
The issue here is that we have an AST structure like:
```
luau.BinaryOperator
luau.IfExpression
luau.StringLiteral
```
this renders as
```lua
if condition then whenTrue else whenFalse .. "string"
```
We need to add parentheses around the if expression so it's properly treated as a "child" expression of the `luau.BinaryExpression`.
To do this, I've used the existing "operator precedence" system (via the function `needsParentheses()` in the renderer). This feels _more_ correct than just tossing parentheses around the expressions in `transformTemplateExpression()`, but I'm not 100% sure this covers all cases. Are there other expression types that also have this issue and we haven't considered them?
[playground link](https://roblox-ts.com/playground/#code/DYUwLgBA9gdhC8EwCcCuIDcAoLB6XEARqgOYBc …
> Fix Luau if-expression precedence bug

- src/TSTransformer/classes/TransformState.ts
- src/TSTransformer/nodes/class/transformClassLikeDeclaration.ts
- src/TSTransformer/nodes/class/transformDecorators.ts
- src/TSTransformer/nodes/transformMethodDeclaration.ts
- src/TSTransformer/util/types.ts
- src/TSTransformer/util/validateNotAny.ts
- tests/package-lock.json
- tests/package.json
Fixes #1790
Until the types are added to `@rbxts/compiler-types`, you'll need a `types.d.ts` file with:
```TS
export {};
declare global {
type InferThis<T> = T extends (this: infer U, ...parameters: Array<any>) => any ? U : never;
type Parameters2<T> = T extends (...args: infer P) => any ? P : never;
type ReturnType2<T> = T extends (...args: Array<any>) => infer R ? R : never;
interface TypedPropertyDescriptor<T> {
value: (self: InferThis<T>, ...parameters: Parameters2<T>) => ReturnType2<T>;
}
}
```
`Parameters2` and `ReturnType2` just remove the `extends Callback` constraint.
> Add support for decorators

- src/README.md
These are linking to files that doesn't exist anymore due to the compiler split.
> Fix LuauAST/LuauRenderer link in src/README.md

- src/Project/functions/validateCompilerOptions.ts
The previous implementation of `validateTypeRoots` only `path.resolve`'d the `nodeModulesPath` which would cause an error when when using `VirtualProject`.
`VirtualProject` uses `/node_modules/@rbxts` which get normalized to `\node_modules\@rbxts` (within `validateTypeRoots`)
but the first parameter `nodeModulesPath` is already normalized from the caller
`\node_modules\@rbxts` and then gets resolved to `C:\node_modules\@rbxts`.
Which causes the compare to fail
`path.normalize(typeRoot) === typesPath`
`path.normalize('/node_modules/@rbxts') === 'C:\\node_modules\\@rbxts'`
`'\\node_modules\\@rbxts' === 'C:\\node_modules\\@rbxts'`
The solution is to `path.resolve` both variables.
> Use path.resolve on both parameters in validateTypeRoots

- src/TSTransformer/macros/propertyCallMacros.ts
#1864 missed a few incorrect luau.none usages
https://roblox-ts.com/playground/#code/MYewdgzgLgBAhjAvDA2gXQHQDMQCcCicwAFgBSkCUSAfDAN4C+FA3AFCiSwBGSqmwAGwCmcXJTYdoMYLzBCA7jACycAA6VseQiXJVEtRi3bgpAE1kKYAZSFQNOAkTKUa9JhJOwhFxTbsUMQRExI0lYLB9lNQ0g0XEgA
> Fix luau.none usage in macros

- src/TSTransformer/macros/propertyCallMacros.ts
- src/TSTransformer/nodes/transformWritable.ts
Adapting to the changes from roblox-ts/luau-ast#69
These are all cases where `pushToVarIfComplex` is used, but this does not push `false` and other literals, which are not indexable. These values are then used in cases that only accept indexable expressions, syntax-wise.
Also in all cases, the literals never appear without @ts-ignore comments, which will cause assertion fail while rendering. The only other simple node kinds are Identifier and TemporaryIdentifier. Therefore, switching to `pushToVarIfNonId` is not a change in behaviour.
> Fix errors detected by luau.Node type change

- src/TSTransformer/nodes/binding/transformArrayBindingPattern.ts
- src/TSTransformer/nodes/binding/transformObjectBindingPattern.ts
- src/TSTransformer/nodes/statements/transformImportDeclaration.ts
- src/TSTransformer/nodes/statements/transformImportEqualsDeclaration.ts
- src/TSTransformer/nodes/statements/transformVariableStatement.ts
Remove the internal `state.capture()` and hoist it to each callsite to either be `state.capture()` or `state.capturePrereqs()`
> Refactor transformVariable

- src/CLI/commands/build.ts
- src/CLI/test.ts
- src/Project/classes/VirtualProject.ts
- src/Project/functions/compileFiles.ts
- src/Project/preEmitDiagnostics/fileUsesCommentDirectives.ts
- src/Project/util/getCustomPreEmitDiagnostics.ts
- src/Shared/constants.ts
- src/Shared/diagnostics.ts
- src/Shared/types.ts
- src/Shared/util/createDiagnosticWithLocation.ts
Bans:
- `@ts-ignore`
- `@ts-expect-error`
- `@ts-nocheck`
Adds a project option / CLI flag: --allowCommentDirectives to skip these checks.
Reworked diagnostics a bit to allow for `ts.SourceFile` + `ts.ReadonlyTextRange` instead of a `ts.Node`
> Ban `@ts-ignore` and add --allowCommentDirectives

- src/Project/classes/VirtualProject.ts
- src/Project/functions/compileFiles.ts
- src/TSTransformer/classes/TransformState.ts
- src/TSTransformer/nodes/statements/transformImportDeclaration.ts
- src/TSTransformer/util/createImportExpression.ts
- src/TSTransformer/util/getSourceFileFromModuleSpecifier.ts
https://github.com/roblox-ts/services/blob/master/plugin.d.ts
Augmented modules cause an assertion failure currently, this PR fixes that by using `ts.getResolvedModule`
> Fix assertion failure on importing augmented modules

- src/Shared/diagnostics.ts
- src/TSTransformer/util/createImportExpression.ts
This warning is broken, but was also covered by the RuntimeLib used in ReplicatedFirst warning already
> Remove packageUsedInReplicatedFirst warning

- package.json
The `test-setup` script negatively affects testing because it always tries installing the most recent types. This makes `npm test` fail for older versions, which can be especially annoying while trying to `git bisect`. The behaviour of testing the current compiler with the newest types is retained in the github CI workflow, which calls the individual test steps separately, and continues to execute `test-setup`.
> Remove test-setup script from main test script

- tests/src/tests/loop.spec.ts
Same as case 7, but inlining the `limit` variable skips the `isProbablyInteger` checks, making the unit test more isolated and hopefully more stable in testing its case.
> Add extra test for numerical for loop

- src/TSTransformer/nodes/statements/transformForStatement.ts
Fixes two broken unit tests by reverting their emit to the unoptimized case.
The previous check allowed `<`, `<=`, `>`, or `>=`.
However, this caused broken behavior with invalid loops that shouldn't actually run:
```ts
for (let i = 3; i <= 1; i -= 1) {
print(i);
}
```
would compile into:
```lua
for i = 3, 1, -1 do
print(i)
end
```
The new check allows:
- `<`, `<=` with `i++`
- `>` and `>=` with `i--`
(or similar incrementors like `i += 5`, etc.)
> Fix broken optimized loop cases where condition doesn't match incrementor

- .eslintrc
- package-lock.json
- package.json
Guards against using deprecated properties/methods/functions, like `node.decorators` since TS 4.8.
> Add eslint-plugin-deprecation

- package-lock.json
- package.json
It was only used by rojo-resolver, but I forgot to remove it when splitting that out.
> Remove ajv

- package-lock.json
- package.json
- src/Project/classes/VirtualProject.ts
- src/Project/functions/createProgramFactory.ts
- src/Project/functions/validateCompilerOptions.ts
- src/Project/transformers/builtin/transformPaths.ts
- src/TSTransformer/nodes/jsx/transformJsxAttributes.ts
- src/TSTransformer/nodes/jsx/transformJsxTagName.ts
- src/TSTransformer/util/jsx/getAttributeName.ts
- src/TSTransformer/util/jsx/getKeyAttributeInitializer.ts
- tests/src/main.server.ts
- tests/tsconfig.json
`ttypescript` was deprecated and does not support TypeScript 5.0+.
Only difference here should be building the compiler with `tspc` instead of `ttsc`.
Previously, we would overwrite `ts.version` with a new string containing compiler version + hashed several inputs including project type, "is package", list of plugins, and Rojo config contents.
TypeScript 5.0 no longer lets us do that because `version` is no longer part of a namespace, but exported from a module.
Instead, I've overwritten the `CompilerHost.createHash` function to include this. Seems to work the same.
A few types in here required a `| undefined` to avoid compiler errors.
Added support for newly introduced type `ts.JsxNamespacedName` which had caused some compiler errors.
A "JSX namespaced name" is something like `<a:b />` …
> Upgrade TypeScript to 5.1.6

- package-lock.json
- package.json
- src/TSTransformer/nodes/statements/transformForOfStatement.ts
Previously, if you used tuple labels TypeScript required all members to have a label. Otherwise, you'd get this error:
```
error TS5084: Tuple members must all have names or all not have names.
```
TypeScript 5.2 removed this requirement so now we have to check if `label` exists before using it.
> TypeScript 5.2.2 Support

- src/TSTransformer/nodes/statements/transformEnumDeclaration.ts
Built on top of the ideas from #2062
- If all members of the enum do not allow reverse lookup, emit a simpler structure:
```ts
enum X {
A = "A",
"B" = "B",
}
```
```lua
local X = {
A = "A",
B = "B",
}
```
- Otherwise, fallback to inverse mapping emit, but only assign to inverse mapping if needed
```ts
enum X {
A = "A",
"B" = "B",
C = 1,
}
```
```lua
local X
do
local _inverse = {}
X = setmetatable({}, {
__index = _inverse,
})
X.A = "A"
X.B = "B"
X.C = 1
_inverse[1] = "C"
end
```
> Remove enum inverse mapping for string values

- tests/src/tests/loop.spec.ts
Covers:
- `$range` without a step value
- `$range` with a negative step value
- `$range` with a decimal step value
closes #2507
> Add unit tests for `$range` macro

- src/TSTransformer/macros/propertyCallMacros.ts
- tests/src/tests/array.spec.ts
The macro currently doesn't create a temporary variable for the target array, which clones the table expression for each insert call and returns the incorrect size of the changed array when it's captured.
This has been happening since the method rework in https://github.com/roblox-ts/roblox-ts/pull/1853.
```ts
print([1, 2, 3].push(4, 5, 6));
```
Current emit:
```lua
-- Compiled with roblox-ts v2.2.0
-- ▼ Array.push ▼
table.insert({ 1, 2, 3 }, 4)
table.insert({ 1, 2, 3 }, 5)
table.insert({ 1, 2, 3 }, 6)
-- ▲ Array.push ▲
print(#({ 1, 2, 3 }))
return nil
```
Expected:
```lua
-- Compiled with roblox-ts v2.2.0
local _exp = { 1, 2, 3 }
-- ▼ Array.push ▼
table.insert(_exp, 4)
table.insert(_exp, 5)
table.insert(_exp, 6)
-- ▲ Array.push ▲
print(#_exp)
return nil
```
> Fix `Array.push` inserting multiple values for different tables

- src/TSTransformer/macros/propertyCallMacros.ts
- tests/src/tests/map.spec.ts
- tests/src/tests/set.spec.ts
Similar to #2597, currently this doesn't create an id for the expression if it's a table literal. The difference is that the result won't change at runtime, but this still is the correct way it should emit.
```ts
const a = new Set(["a", "b"]).delete("a");
const b = new Map<string, number>([
["a", 1],
["b", 2],
]).delete("a");
```
Current emit:
```lua
-- Compiled with roblox-ts v2.2.0
-- ▼ Set.delete ▼
local _valueExisted = ({
["a"] = true,
["b"] = true,
}).a ~= nil
({
["a"] = true,
["b"] = true,
}).a = nil
-- ▲ Set.delete ▲
local a = _valueExisted
-- ▼ Map.delete ▼
local _valueExisted_1 = ({
a = 1,
b = 2,
}).a ~= nil
({
a = 1,
b = 2,
}).a = nil
-- ▲ Map.delete ▲
local b = _valueExisted_1
return nil
```
Expected emit:
```lua
-- Compiled with roblox-ts v2.2.0
local _exp = {
["a"] = true, …
```
> Fix `(Map|Set).delete` expression being cloned

- src/TSTransformer/nodes/expressions/transformCallExpression.ts
- Remove confusing tempId names
- Fix expressionMightMutate usage
```ts
const { Terrain } = game.GetService("Workspace");
{
Terrain.FillBall(Vector3.zero.add(Vector3.zero), 10, Enum.Material.Rock);
}
{
const s = "FillBall";
Terrain[s](Vector3.zero.add(Vector3.zero), 10, Enum.Material.Rock);
}
```
```lua
local _binding = game:GetService("Workspace")
local Terrain = _binding.Terrain
do
local _fn = Terrain
local _zero = Vector3.zero
local _zero_1 = Vector3.zero
_fn:FillBall(_zero + _zero_1, 10, Enum.Material.Rock)
end
do
local s = "FillBall"
local _fn = Terrain
local _zero = Vector3.zero
local _zero_1 = Vector3.zero
_fn[s](_fn, _zero + _zero_1, 10, Enum.Material.Rock)
end
```
In the current emit, `Terrain` is pushed to a tempId and given the name "fn".
I think this is a copy/paste bug from …
> Improve emit for `a.b()` and `a[b]()`

- src/TSTransformer/nodes/class/transformClassLikeDeclaration.ts
Since `shouldUseInternalName` already checks that `node.name !== undefined`, this second check does nothing.
> Fix unnecessary check for internal name

- package-lock.json
- package.json
Latest `@next` where we upgraded from TypeScript 5.2.2 to 5.3.3 breaks the playground.
This is because new triple-slash directives were added for referenced ambient declarations.
We can fix this by making `@types` dependencies instead of devDependencies.
https://github.com/microsoft/TypeScript/pull/56015
> Move @types to be dependencies instead of devDependencies

- src/TSTransformer/util/types.ts
- tests/src/tests/optional.spec.ts
```
TypeError: Cannot read properties of undefined (reading 'declarations')
at roblox-ts/out/tstransformer/util/types.js:198:41
at roblox-ts/out/tstransformer/util/types.js:64:37
at Array.some (<anonymous>)
at isPossiblyTypeInner (roblox-ts/out/tstransformer/util/types.js:64:26)
at roblox-ts/out/tstransformer/util/types.js:49:37
at Array.some (<anonymous>)
at isPossiblyTypeInner (roblox-ts/out/tstransformer/util/types.js:49:27)
at isPossiblyType (roblox-ts/out/tstransformer/util/types.js:69:12)
at fixVoidArgumentsForRobloxFunctions (roblox-ts/out/tstransformer/nodes/expressions/transformCallExpression.js:67:36)
at transformCallExpressionInner (roblox-ts/out/tstransformer/nodes/expressions/transformCallExpression.js:100:5)
```
Regression accidentally introduced by #2672
`type.symbol` will …
> Fix optional function call crash

- eslint.config.ts
Found a better way to do this: https://github.com/prettier/eslint-plugin-prettier?tab=readme-ov-file#configuration-new-eslintconfigjs
This enables `prettier/prettier` as error, so I kept the `"prettier/prettier": "warn",` line
also removed unnecessary `"@typescript-eslint": tseslint.plugin,` (it's already included by `...tseslint.configs.recommended`)
> Simplify prettier usage in eslint.config.ts

- src/TSTransformer/classes/TransformState.ts
Fixes a regression from #2704 - ts.toPath normalises the path. Without it, the path was only found correctly on Unix-like filesystems, since only they use `/` by default.
> Use ts.toPath for guessVirtualPath

- src/Project/functions/compileFiles.ts
- src/Project/transformers/builtin/transformPaths.ts
`transformPaths` broke because `resolver.moduleExportsSomeValue()` no longer exists in TypeScript (and is not trivial to copy from an old version).
Originally, I tried to just `npm install` the latest version, but this had a few issues:
- TypeScript wasn't able to find types because of how the package.json is setup, I was able to hack around this with a `// @ts-ignore`
- Newest version seems to not respect just `baseUrl`, it requires you have a `paths` in your tsconfig.json (and many roblox-ts projects don't)
I also can't just copy over the latest file from the repo because it has a bunch of imports.
Instead, I found a slightly newer version which doesn't use `moduleExportsSomeValue` and is still a single file. This required a few small fixes i.e. removing non-ts.factory APIs.
---
The …
> Fix transformPaths transformer

- package-lock.json
- package.json
- src/CLI/commands/build.ts
- src/CLI/test.ts
- src/Project/classes/VirtualProject.ts
- src/Project/functions/createPathTranslator.ts
- src/Project/functions/setupProjectWatchProgram.ts
- src/Shared/constants.ts
- src/Shared/types.ts
- tests/default.project.json
Depends on:
- https://github.com/roblox-ts/path-translator/pull/2
- https://github.com/roblox-ts/rojo-resolver/pull/496
Allows for both emitting .luau files to `outDir` and importing packages contain `.luau` files (or `.lua` for backwards compatibility).
Unit tests pass with the above two PR branches installed locally.
> Add support for `.luau`

- src/CLI/cli.ts
This was removed in https://github.com/roblox-ts/roblox-ts/commit/553259333b450a284a5f6bce7349ed36bc3e353b because we thought it was effectively the same as the default behavior.
One key difference we missed: custom .fail() uses `console.log()` which automatically calls `.toString()` on the error. For custom error classes like CLIError, this is where we do the formatting for the output.
I've added it back + added a clarifying comment.
> Add back `yargs.fail()`

- src/TSTransformer/util/wrapReturnIfLuaTuple.ts
- tests/src/tests/destructure.spec.ts
- tests/src/tests/tuple.spec.ts
#2929 added a fix for `foo()?.[0]` where `foo()` returns a `LuaTuple<T>`
When reviewing that PR, I discovered a few additional cases:
1. `const [a, b, ...rest] = foo();`
2. `[a, b, ...rest] = foo();`
3. `const [a, b, c] = foo?.();`
4. `[a, b, c] = foo?.();`
```ts
function returnsLuaTuple() {
return $tuple(1, 2, 3, 4, 5);
}
// luatuple + spread + array binding pattern
{
const [a, b, ...rest] = returnsLuaTuple();
}
// luatuple + spread + array assignment pattern
{
let a: number;
let b: number;
let rest: number[];
[a, b, ...rest] = returnsLuaTuple();
}
// luatuple + optional function call + array binding pattern
{
const [a, b, c] = returnsLuaTuple?.();
}
// luatuple + optional function call + array assignment pattern
{
let a: number;
let b: number;
let c: number;
[a, b, c] = …
```
> Additional fixes for `shouldWrapLuaTuple()`

- src/TSTransformer/nodes/statements/transformVariableStatement.ts
- src/TSTransformer/util/binding/getTargetIdForBindingPattern.ts
- tests/src/tests/destructure.spec.ts
Simple change. Using `pushToVarIfNonId` to reference the value from binding patterns eliminates the need of creating a new variable every time the value is indexed if it's already an ID.
Non-null assertions are used there because currently TypeScript doesn't remember the type narrowing changes you made before when using the variable inside a nested callback. See https://github.com/microsoft/TypeScript/issues/36436.
```ts
const omg = [1, 2, 3, 4, 5];
const [one, two] = omg;
const ok = { foo: true, bar: false };
const { foo, bar } = ok;
const { baz } = { baz: "hello" };
```
```luau
-- Checking to see if it's an id first
local omg = { 1, 2, 3, 4, 5 }
local one = omg[1]
local two = omg[2]
local ok = {
foo = true,
bar = false,
}
local foo = ok.foo
local bar = ok.bar
local _binding = {
baz = …
```
> Optimize binding pattern emit for variable creation
