- src/class/Compiler.ts
> Support Rojo partitions relative to baseUrl

- .gitmodules
- .travis.yml
- package-lock.json
- package.json
- spec.lua
- src/class/Transpiler.ts
- src/index.ts
- tests/spec/math.spec.lua
- tests/src/math.ts
- tests/tsconfig.json
- tslint.json
This pull request will solve #10.
Current plans
> CI with TravisCI (WIP)

- .luacheckrc
- tests/spec/class.spec.lua
- tests/spec/enum.spec.lua
- tests/src/class.ts
- tests/src/enum.ts
This PR adds enum and class tests. It also makes all test code Luacheck ok.
> Expand tests

- README.md
- src/class/Compiler.ts
- src/class/Transpiler.ts
- src/index.ts
- src/utility.ts
> [WIP] Errors for files requiring files they shouldn't be able to, accessing APIs they shouldn't be able to

- src/class/Transpiler.ts
Take a look at the changes. There are still a few things that need to be accounted for:
- While statements don't transpile correctly
- If statements don't transpile correctly
This is a good start though.
> Upgrade prefix unary operations

- src/class/Transpiler.ts
I think this is pretty much ready for master. The only thing that could be improved is `this.getPrefixUnaryMaps()` should get called more often in order to detect when it is unnecessary to make the last local variable.
> Reduce complexity, fix remaining problems

- .travis.yml
- package.json
Instanbul has inconsistent docs, this is the best I can do.
> Update tests for better practices

- include/RuntimeLib.lua
- src/class/Transpiler.ts
Functions should all go within a single table within TS
> Remove depth from Runtimelib

- src/class/Transpiler.ts
This should fix Static methods and static inheritance. Static members should also be properly inherited now.
The only thing left to work out is static getters and setters.
> Fix Static methods, static inheritance

- package-lock.json
- package.json
- src/class/Compiler.ts
- src/class/Transpiler.ts
- src/class/errors/TranspilerError.ts
- src/test.ts
- tests/package-lock.json
- tests/package.json
- tests/spec.lua
- tests/src/errors/roactClassGet.spec.tsx
- tests/src/errors/roactClassSet.spec.tsx
- tests/src/errors/roactJsxText.spec.tsx
- tests/src/errors/roactSubClass.spec.tsx
- tests/src/roact.spec.tsx
- tests/tsconfig.json
Work In Progress. 
Definitely do not use for any production stuff yet. Things are hugely subject to change.
Issue: https://github.com/roblox-ts/roblox-ts/issues/20
Definitions: https://github.com/Vorlias/rbx-roact/blob/master/index.d.ts (WIP as well)
> Support Roact Classes & .tsx

- include/RuntimeLib.lua
- package-lock.json
- package.json
- src/class/Transpiler.ts
- tests/src/instance_values.spec.ts
> Implement Roblox instance values

- src/class/Compiler.ts
An actual message should show now.
> Fixed diagnostic errors showing as [object Object]

- src/class/Transpiler.ts
- tests/src/roact_spread.spec.tsx
Allows usage of 
`<frame {...value}/>`
and
`<MyComponent {...value}/>`
This will especially be good for setting preset values on multiple Roact elements. 😃
> Jsx spread attribute

- src/class/Transpiler.ts
- src/class/errors/TranspilerError.ts
- tests/src/errors/roactJsxText.spec.tsx
> TranspilerError on JSX usage without importing Roact

- include/RuntimeLib.lua
- Add better error messages
- Avoid table creation (prefer select instead)
- Prefer numeric for loop to pairs
- Prefer `ClassName` check to `IsA`
> Improve TS.import

- src/class/Transpiler.ts
Fixes #127
Fixes #164
Fixes #173
> Make `_exports`  and `undefined` reserved identifiers

- src/class/Transpiler.ts
> Fix compiled Vector3 operator precedence

- src/class/Transpiler.ts
> Fix Invalid lua generated by export

- src/class/Transpiler.ts
<h3>Overview:</h3>
- Fixed For loops problem where updating a locally scoped version of the iterator variable would not update the actual iterator
- Fix For loops problem with checking its ancestors for function definitions when it was supposed to be checking its descendants.
- Fix problems with `getFirstFunctionLikeAncestor` not detecting functions properly (which affected for loops inside constructors, for example), and consolidate into `getFirstMemberWithParameters` which can accept an array of either descendants or ancestors depending on what you need to search.
- Created intial working code that checks whether a For loop can be optimized to a simple for loop
- Optimized functions with vararg tuples which don't need to generate `local ${name} = {...}`. If the only times `name` is used …
> For loop optimization start

- src/transpiler/loop.ts
> Fix non-identifiers in forOf loops (ready to merge)

- src/errors/TranspilerError.ts
- src/transpiler/binding.ts
- src/transpiler/call.ts
- src/transpiler/function.ts
- src/transpiler/identifier.ts
- src/transpiler/indexed.ts
- src/transpiler/security.ts
- src/transpiler/variable.ts
- src/typeUtilities.ts
> Add guards against using type "any"

- src/transpiler/binary.ts
- src/transpiler/binding.ts
- src/transpiler/call.ts
- src/transpiler/expression.ts
- src/transpiler/function.ts
- src/transpiler/identifier.ts
- src/transpiler/indexed.ts
- src/transpiler/security.ts
- src/transpiler/variable.ts
- tests/src/destructure.spec.ts
- tests/src/testez.d.ts
- tests/src/testez.spec.ts
- improve any checks, less strict
- compile calls with information from the "this" parameter
- compile methods with information from the "this" parameter
> improve any checks

- src/transpiler/module.ts
- src/typeUtilities.ts
Fixes regressions made [here](https://github.com/roblox-ts/roblox-ts/blob/edf5580d76a7ea4f93b7e02cb9c8191f897388e2/src/transpiler/module.ts#L213) and [here](https://github.com/roblox-ts/roblox-ts/blob/edf5580d76a7ea4f93b7e02cb9c8191f897388e2/src/transpiler/module.ts#L294).
Fixes #232
> Fix import regression

- package-lock.json
- package.json
- src/Compiler.ts
- src/TranspilerState.ts
- src/index.ts
- src/transpiler/sourceFile.ts
- src/typings/luamin.d.ts
Adds --minify/--min option to run the emitted source through luamin
~~This doesn't minify Lua source files that are passed through from the src folder. Perhaps it should?~~
Runs all Lua source files through luamin, including compiled TS, Lua passthrough files, and modules. However, the runtime lib is not due to a luamin bug which removes parenthesis where it shouldn't, which breaks some of our code.
Closes #276
> Add minify option

- package-lock.json
- src/transpiler/call.ts
- src/transpiler/indexed.ts
- src/transpiler/spread.ts
- src/typeUtilities.ts
- tests/src/tuple.spec.ts
> Fix LuaTuple problems

- src/transpiler/indexed.ts
> Numeric literal fix

- src/transpiler/loop.ts
- tests/src/loop.spec.ts
> Do while scope fix

- src/transpiler/binding.ts
- src/transpiler/class.ts
Fixes https://github.com/roblox-ts/roblox-ts/issues/320
> Constructor parameter initializer fix

- src/compiler/call.ts
- src/errors/CompilerError.ts
Nitpick, but it makes compilation more consistent
> Allow math macros as expression statements

- src/compiler/new.ts
Fixes https://github.com/roblox-ts/roblox-ts/issues/355
> Set spacing fix

- src/compiler/class.ts
- src/errors/CompilerError.ts
Closes https://github.com/roblox-ts/roblox-ts/issues/350
> Disallow static new method

- src/compiler/identifier.ts
- src/compiler/security.ts
- src/errors/CompilerError.ts
Fixes https://github.com/roblox-ts/roblox-ts/issues/362
> disallow globalThis

- lib/RuntimeLib.lua
> Add array_includes

- src/compiler/call.ts
- src/compiler/expression.ts
- src/compiler/new.ts
- src/compiler/statement.ts
- src/compiler/switch.ts
- src/typeUtilities.ts
- src/utility.ts
- tests/src/map.spec.ts
Fixes https://github.com/roblox-ts/roblox-ts/issues/352
Fixes https://github.com/roblox-ts/roblox-ts/issues/381
Also, added one line and a test for this:
Fixes https://github.com/roblox-ts/roblox-ts/issues/373
> Fix switch statement cases which require precedingStatementContexts

- src/Project.ts
- src/errors/ProjectError.ts
- tests/package-lock.json
- tests/package.json
> enforce minimum rbx-types version

- src/Project.ts
- src/compiler/binding.ts
- src/compiler/call.ts
- src/compiler/indexed.ts
- src/errors/CompilerError.ts
- src/test.ts
- src/typeUtilities.ts
- tests/package.json
- tests/src/array.spec.ts
- tests/src/destructure.spec.ts
- tests/src/errors/methodDestructure/union.spec.ts
- tests/src/errors/tupleLength1.spec.ts
- tests/src/errors/tupleLength2.spec.ts
- tests/src/errors/tupleLength3.spec.ts
- tests/src/literal.spec.ts
- tests/src/object.spec.ts
- tests/src/string.spec.ts
- tests/src/template.spec.ts
Fixes https://github.com/roblox-ts/roblox-ts/issues/426
> length() => size() and fix Array/Object union indexing

- src/compiler/conditional.ts
- src/compiler/if.ts
- src/errors/CompilerError.ts
- src/test.ts
- tests/src/errors/luaTupleInConditional.spec.ts
- tests/src/errors/luaTupleInElseIf.spec.ts
- tests/src/errors/luaTupleInIf.spec.ts
Fixes https://github.com/roblox-ts/roblox-ts/issues/349
> Disallow LuaTuples in conditionals

- src/Project.ts
- src/compiler/call.ts
- src/compiler/forOf.ts
- tests/package-lock.json
- tests/package.json
- tests/src/destructure.spec.ts
- tests/src/robloxEnum.spec.ts
Adds support for Enum.GetEnums() and EnumType.GetEnumItems()
> Whitelist Enum namespace functions as methods

- lib/RuntimeLib.lua
- tests/src/string.spec.ts
Fixes https://github.com/roblox-ts/roblox-ts/issues/438
> Find wrap fix

- src/compiler/binary.ts
- src/compiler/binding.ts
- src/compiler/class.ts
- src/compiler/roact.ts
- src/errors/CompilerError.ts
- tests/package-lock.json
- tests/package.json
- tests/src/class.spec.ts
Simplifies the class structure.
Wraps in do-end only when needed.
> Simplify classes

- lib/RuntimeLib.lua
- package-lock.json
- src/Project.ts
- src/compiler/forOf.ts
- src/test.ts
- tests/src/destructure.spec.ts
- tests/src/errors/requireGmatchForOfDestructure.spec.ts
- tests/src/loop.spec.ts
Requires https://github.com/roblox-ts/rbx-types/pull/102
After merging the rbx-types PR, project.ts should be updated to have `MINIMUM_RBX_TYPES_VERSION = 223`
Fixes https://github.com/roblox-ts/roblox-ts/issues/469
> Gmatch destructuring in for of loops

- src/Project.ts
- src/Watcher.ts
- src/compiler/class.ts
- src/compiler/new.ts
- src/compiler/roact.ts
- src/compiler/security.ts
- src/errors/CompilerError.ts
- src/errors/LoggableError.ts
- src/errors/ProjectError.ts
- src/test.ts
- src/textUtilities.ts
- src/utility.ts
> Improve error logging, recover from ts-morph crash

- src/Initializer.ts
- src/Watcher.ts
- src/cli.ts
- src/errors/CliError.ts
- src/utility/general.ts
- templates/bundle/default.project.json
- templates/bundle/src/index.server.ts
- templates/bundle/tsconfig.json
- templates/game/default.project.json
- templates/game/src/client/main.client.ts
- templates/game/src/server/main.server.ts
- templates/game/src/shared/module.ts
- templates/game/tsconfig.json
- templates/package/src/index.ts
- templates/package/tsconfig.json
- tsconfig.json
> Add init command

- CHANGELOG.md
- package-lock.json
- package.json
- src/Project.ts
- src/analytics.ts
- src/cli.ts
- src/errors/CompilerError.ts
- src/errors/ProjectError.ts
Logging three types of events
`Compiler success` - for when a project is successfully compiled (helps us track active users)
`CompilerError`, `ProjectError` - helps find top errors users are running into
`rbxtsc --noAnalytics` will opt out of analytics tracking. Saves in local storage.
> Add analytics

- src/Watcher.ts
Fixes https://github.com/roblox-ts/roblox-ts/issues/593
> Add has update all succeeded check

- package-lock.json
- src/compiler/new.ts
- tests/src/map.spec.ts
- tests/src/set.spec.ts
Fixes https://github.com/roblox-ts/roblox-ts/issues/586
> Fix ReadonlyMap and ReadonlySet constructors

- lib/RuntimeLib.lua
- Stores `loadedLibraries[module] = true` before requiring, that way subsequent calls will not check for circular dependencies or register `_G[module] = TS`
- Removes the caching of returned values for each module. Not worth it to create a table with a `data` field for each required module. `require` internally stores the data anyways, so we won't see much performance benefit (if any) by storing the returned data in tables. This allows us to return `require(module)` everytime (automatically yields for the library to resolve if necessary).
> Proposed import solution 1

- lib/RuntimeLib.lua
Unused now that try uses pcall
Closes #624
> Remove TS.throw/try

- src/compiler/call.ts
- src/compiler/function.ts
> Fix this: void incorrect emit

- src/compiler/function.ts
- src/compiler/statement.ts
Fixes https://github.com/roblox-ts/roblox-ts/issues/528
> Give constructors hoistStack power

- src/compiler/class.ts
Closes https://github.com/roblox-ts/roblox-ts/issues/536
> Disallow new method

- CHANGELOG.md
- src/Project.ts
Copies libraries without the @rbxts namespace
> Copy files to include without @rbxts

- lib/Promise.lua
> Make new bindable use Promise.spawn

- .luacheckrc
- CHANGELOG.md
- lib/RuntimeLib.lua
- src/compiler/module.ts
- Adds a way to work around Roblox replication problems. Is this useful?
- Fixes https://github.com/roblox-ts/roblox-ts/issues/678
Let's merge this on the day we release v3.0
> Transition to requiring script as first param, ensure node_modules are replicated

- lib/RuntimeLib.lua
Fixes https://github.com/roblox-ts/roblox-ts/issues/714
> Allow array_every's callback to return nil values

- src/compiler/call.ts
> Remove comments for Array.pop and Array.unorderedRemove

- .vscode/extensions.json
- .vscode/settings.json
> Update vscode to override global overrides

- .gitattributes
Source: https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings
It makes it work for me 👍
> Update gitattributes eol=lf

- lib/RuntimeLib.lua
https://github.com/roblox-ts/types/pull/219
> Add Object.fromEntries

- src/CLI/cli.ts
- src/CLI/commands/build.ts
- src/CLI/commands/init.ts
- src/CLI/modules/Watcher.ts
- src/LuaAST/impl/create.ts
- src/LuaRenderer/RenderState.ts
- src/LuaRenderer/render.ts
- src/Project/Project.ts
- src/Shared/RojoConfig.ts
- src/Shared/constants.ts
- src/Shared/diagnostics.ts
- src/Shared/fsUtil.ts
- src/Shared/util/arrayStartsWith.ts
- src/Shared/util/assert.ts
- src/Shared/util/findLastIndex.ts
- src/Shared/util/formatDiagnostics.ts
- src/Shared/util/getOrSetDefault.ts
- src/Shared/warn.ts
- src/TSTransformer/classes/MacroManager.ts
- src/TSTransformer/classes/TransformState.ts
- src/TSTransformer/macros/propertyCallMacros.ts
- src/TSTransformer/nodes/statements/transformStatement.ts
- src/TSTransformer/nodes/transformSourceFile.ts
- src/TSTransformer/nodes/transformStatementList.ts
- src/TSTransformer/util/createGetService.ts
Document significant logic inside the project structure. Skipped over self-explanatory methods such as exported transformer and rendering functions.
> Add documentation

- src/TSTransformer/README.md
- src/TSTransformer/macros/propertyCallMacros.ts
TS:
```ts
let myFoundThing = frameworks.find((val) => {
return true
})
```
produces this in Lua:
```lua
-- ▼ ReadonlyArray.find ▼
local _1 = function(val)
return true
end
local _2 = nil
for _3, _4 in ipairs(frameworks) do
if _1(_4, _3 - 1, frameworks) == true then
_2 = _4
break
end
end
-- ▲ ReadonlyArray.find ▲
local myFoundThing = _1
```
Credit to @Dionysusnu for helping me fix type errors and returning what was found within the loop.
> Add readonlyArray.find macro

- src/TSTransformer/README.md
- src/TSTransformer/macros/propertyCallMacros.ts
Should this and Object.copy() be merged into 1 function? Or is it fine with them being separate?
> add readonlyArray.copy()

- .eslintrc
Discussed on discord.
CI will probably fail.
> Add "no-unused-expressions" warn to eslint

- src/Project/Project.ts
- src/Project/util/validateCompilerOptions.ts
- src/Shared/diagnostics.ts
- src/TSTransformer/classes/CompileState.ts
- src/TSTransformer/preEmitDiagnostics/fileIsModule.ts
> Add custom module check, remove --isolatedModules requirement

- src/TSTransformer/macros/propertyCallMacros.ts
Since Luau now has compound assignment operators
> Change Map.size() to use +=

- src/TSTransformer/nodes/expressions/transformCallExpression.ts
string.byte should be wrapped as it returns a tuple
> Wrap macro return if lua tuple

- tests/src/tests/delete.spec.ts
For more completeness!
Tests the following this:
Additionally, every test comes with a parenthesized expression
> Create unit tests for `delete` operator

- src/LuauAST/impl/List.ts
- src/TSTransformer/nodes/statements/transformForStatement.ts
- Fixed an issue with the incrementor not being called before a continue
- Fixed an issue with the incrementer sometimes being put after a return
Credit to @Dionysusnu for list copy method.
> For loop incrementor fixes

- package-lock.json
- package.json
- src/TSTransformer/classes/RoactSymbolManager.ts
- src/TSTransformer/classes/TransformState.ts
- src/TSTransformer/nodes/expressions/transformBinaryExpression.ts
- src/TSTransformer/nodes/expressions/transformConditionalExpression.ts
- src/TSTransformer/nodes/expressions/transformObjectLiteralExpression.ts
- src/TSTransformer/nodes/jsx/transformJsxAttributes.ts
- src/TSTransformer/nodes/statements/transformExpressionStatement.ts
- src/TSTransformer/nodes/transformLogical.ts
- src/TSTransformer/util/assignment.ts
- src/TSTransformer/util/createTruthinessChecks.ts
- src/TSTransformer/util/types.ts
Adds isPossiblyType function to help determine if a given type _could_ be another.
> Remove ts-simple-type

- src/LuauAST/impl/create.ts
- src/TSTransformer/classes/TransformState.ts
- src/TSTransformer/nodes/expressions/transformBinaryExpression.ts
- src/TSTransformer/nodes/expressions/transformConditionalExpression.ts
- src/TSTransformer/nodes/expressions/transformObjectLiteralExpression.ts
- src/TSTransformer/nodes/jsx/transformJsxChildren.ts
- src/TSTransformer/util/createTruthinessChecks.ts
- src/TSTransformer/util/createTypeCheck.ts
- src/TSTransformer/util/types.ts
> Improve JSX child expression emit

- src/TSTransformer/macros/propertyCallMacros.ts
> Generate calls to table.create over {}

- src/LuauRenderer/nodes/statements/renderAssignment.ts
- src/LuauRenderer/nodes/statements/renderVariableDeclaration.ts
> Add asserts for empty variable lists in Assignment and VariableDeclaration

- src/TSTransformer/classes/TransformState.ts
- src/TSTransformer/nodes/statements/transformImportDeclaration.ts
- src/TSTransformer/nodes/transformSourceFile.ts
> Simplify exports logic

- src/Shared/diagnostics.ts
- src/TSTransformer/nodes/expressions/transformCallExpression.ts
- src/TSTransformer/nodes/expressions/transformExpression.ts
- src/TSTransformer/nodes/expressions/transformImportExpression.ts
- src/TSTransformer/nodes/transformOptionalChain.ts
Adds support for dynamic import expressions.
```ts
import("../module").then((module) => ...);
```
> Add import expression support

- src/TSTransformer/nodes/expressions/transformExpression.ts
- src/TSTransformer/nodes/expressions/transformOmittedExpression.ts
`[,a]` =sugar= `[undefined,a]`
> Add omitted expression

- src/Shared/diagnostics.ts
- src/TSTransformer/classes/MacroManager.ts
- src/TSTransformer/nodes/expressions/transformObjectLiteralExpression.ts
- src/TSTransformer/nodes/expressions/transformSpreadElement.ts
Wasn't sure how to explain the error fix suggestion, feel free to change that bit
> Ban macro classes being used in object spread

- src/TSTransformer/nodes/expressions/transformArrayLiteralExpression.ts
remnant of me attempting a larger change but failing
> small simplification

- src/CLI/commands/init.ts
> Add default scripts to package.json on init

- src/Shared/diagnostics.ts
- src/TSTransformer/nodes/statements/transformForOfStatement.ts
Fixes the assertion failure in #1253.
> Fix assertion failure with complex for-of variable list

- src/CLI/commands/build.ts
- src/CLI/commands/init.ts
- src/CLI/test.ts
- src/Project/classes/VirtualProject.ts
- src/Project/functions/createProjectData.ts
- src/Shared/types.ts
- src/TSTransformer/macros/propertyCallMacros.ts
This behavior was changed quite a while ago. It's likely no one uses this flag anymore and we can clean it up.
> Remove --logStringChanges

- src/LuauAST/impl/create.ts
- src/LuauAST/impl/typeGuards.ts
- src/LuauAST/types/nodes.ts
- src/TSTransformer/classes/TransformState.ts
- src/TSTransformer/nodes/expressions/transformIdentifier.ts
- src/TSTransformer/nodes/statements/transformForStatement.ts
- src/TSTransformer/nodes/statements/transformVariableStatement.ts
- src/TSTransformer/nodes/transformSourceFile.ts
- src/TSTransformer/util/getDeclaredVariables.ts
- src/TSTransformer/util/traversal.ts
> Improved support for ts.ForStatement

- src/Project/functions/compileFiles.ts
https://www.diffchecker.com/VdqzbR7H
> Fix emitted type declarations with transformers

- src/Project/functions/validateCompilerOptions.ts
> remove JSX tsconfig errors

- src/CLI/commands/build.ts
- src/Project/functions/compileFiles.ts
- src/Project/functions/setupProjectWatchProgram.ts
- src/Project/util/isCompilableFile.ts
- src/Project/util/walkDirectorySync.ts
> Fix watch mode not recompiling after error

- src/Project/transformers/createTransformerList.ts
- src/Shared/diagnostics.ts
Diagnostic message is a bit awkward - open to suggestions to improve it
> Add warning for transformers failing to initialise

- src/TSTransformer/nodes/expressions/transformConditionalExpression.ts
- tests/src/tests/literal.spec.ts
- tests/src/tests/ternary.spec.ts
https://roblox-ts.com/playground/#code/DYUwLgBAHhC8EEYAMBuAsAKBgfggbQF0A6AY1AEMAnACgEoIAuaFIA
> Fix conditional truthiness with prereqs

- src/TSTransformer/nodes/expressions/transformCallExpression.ts
- tests/src/tests/roblox.spec.ts
https://roblox-ts.com/playground/#code/OYQwtgpg2gRAIhAzgFwE4HsCeMC6AKASiA
> Fix element call expression on Roblox types

- src/TSTransformer/nodes/expressions/transformIdentifier.ts
> Fix missing hoist on arrow function variable

- src/TSTransformer/nodes/expressions/transformConditionalExpression.ts
```TS
declare class Run {
IsRunning(): boolean;
On(): void;
Off(): void;
}
const run = new Run();
run.IsRunning() ? run.On() : run.Off();
```
```Lua
local run = Run.new()
local _ = if run:IsRunning() then run:On() else run:Off()
```
```Lua
local run = Run.new()
if run:IsRunning() then
run:On()
else
run:Off()
end
```
> Improved emit for expression statement ternaries

- src/CLI/commands/init.ts
> add git check in init

- src/TSTransformer/nodes/transformLogical.ts
Comment removed:
- "wrapConditional" seems outdated, can't find the name referenced anywhere
- "cannot inline" becomes outdated, because now we sometimes do
> Use inline nullish coalescing if Lua truthiness allows

- src/TSTransformer/util/addOneIfArrayType.ts
- src/TSTransformer/util/binding/getAccessorForBindingType.ts
Doesn't cover anything since #1822
> Remove redundant ts.isArray checks

- src/TSTransformer/classes/DiagnosticService.ts
- src/TSTransformer/classes/MultiTransformState.ts
- src/TSTransformer/classes/TransformState.ts
- src/TSTransformer/nodes/expressions/transformJsxFragment.ts
- src/TSTransformer/nodes/jsx/transformJsx.ts
> Fix broken JSX option checks

- src/TSTransformer/classes/RoactSymbolManager.ts
- src/TSTransformer/classes/TransformState.ts
- src/TSTransformer/nodes/class/transformClassLikeDeclaration.ts
- src/TSTransformer/nodes/jsx/transformJsxAttributes.ts
- src/TSTransformer/nodes/statements/transformImportDeclaration.ts
- src/TSTransformer/nodes/transformSourceFile.ts
- src/TSTransformer/util/extendsRoactComponent.ts
- src/TSTransformer/util/getOriginalSymbol.ts
- src/TSTransformer/util/getOriginalSymbolOfNode.ts
- src/TSTransformer/util/validateNotAny.ts
- tests/package-lock.json
- tests/package.json
- tests/src/tests/roact.spec.tsx
- tests/src/tests/roact_spread.spec.tsx
[playground repro](https://roblox-ts.com/playground/#code/JYWwDg9gTgLgBAJQgQwMbwGZQiOAiAASgCMAPGAZwHps0Y8BuAKCeADsYBTKDNTuAGIQIABWxgKcAN5MAkAFEAbpw4AuRACEAGgGVUUYGBg7gAczbIANswC+LVBDYV4QiOqR0AdAICubdMCOAMI4kGwqMAA8rmIQEgB8cAC8cGDikkmJkVjIIPxU8cxMVFRwxD6mTA5O8JwAjMlw0cJwShFJUqa5nJ5BABbAlgAmAIJDQ5xDNnAFRSVwDlBQnOhVjs5wnABMjdlQ3a3KHB1ScP2Do+OT6gAUAJTJiVLTNtOzTEA)
> Improve Roact Change/Event attribute detection with symbols

- src/CLI/commands/build.ts
- src/CLI/commands/init.ts
- src/CLI/test.ts
- src/Project/classes/VirtualProject.ts
- src/Project/functions/createProjectData.ts
- src/Shared/types.ts
- src/TSTransformer/nodes/statements/transformForStatement.ts
Currently behind a CLI flag: `--optimizedLoops`
> Experimental Optimized Numeric For Loops

- src/Shared/diagnostics.ts
- src/TSTransformer/classes/MacroManager.ts
- src/TSTransformer/macros/callMacros.ts
- src/TSTransformer/nodes/statements/transformForOfStatement.ts
> `$range` macro

- src/Shared/diagnostics.ts
- src/TSTransformer/classes/MacroManager.ts
- src/TSTransformer/macros/callMacros.ts
- src/TSTransformer/nodes/expressions/transformFunctionExpression.ts
- src/TSTransformer/nodes/statements/transformReturnStatement.ts
> `$tuple` macro

- src/TSTransformer/nodes/expressions/transformIdentifier.ts
- src/TSTransformer/nodes/statements/transformImportEqualsDeclaration.ts
- tests/src/diagnostics/noInvalidIdentifier.3.ts
- tests/src/diagnostics/noReservedIdentifier.3.ts
> Add support for `ts.ImportEqualsDeclaration` with `ts.EntityName`

- src/CLI/test.ts
> Clear tests outDir before running

- src/TSTransformer/macros/constructorMacros.ts
- src/TSTransformer/macros/propertyCallMacros.ts
- src/TSTransformer/nodes/expressions/transformObjectLiteralExpression.ts
- src/TSTransformer/nodes/jsx/transformJsxAttributes.ts
- src/TSTransformer/nodes/jsx/transformJsxChildren.ts
- src/TSTransformer/nodes/statements/transformExportDeclaration.ts
- src/TSTransformer/nodes/statements/transformForOfStatement.ts
- src/TSTransformer/util/getAddIterableToArrayBuilder.ts
> Remove all reference to `pairs()`/`ipairs()`

- src/TSTransformer/util/createImportExpression.ts
> Fix non-game host package imports

- src/TSTransformer/nodes/expressions/transformIdentifier.ts
Reverts roblox-ts/roblox-ts#1987
> Revert "Support identifiers that have no symbol"

- src/CLI/commands/init.ts
> Fix PNPM init command failed

- src/Project/classes/VirtualProject.ts
> Fix playground RojoResolver

- src/Shared/diagnostics.ts
- src/TSTransformer/nodes/expressions/transformBinaryExpression.ts
- src/TSTransformer/nodes/expressions/transformCallExpression.ts
- src/TSTransformer/util/isInsideRoactComponent.ts
- src/TSTransformer/util/isSymbolFromRobloxTypes.ts
Based off of #2224 because of related util split - will have to see if squash merge results in conflicts
> Ban instanceof on roblox types

- src/TSTransformer/util/createImportExpression.ts
> Disable networkType check for dynamic `import()`

- src/TSTransformer/nodes/class/transformClassLikeDeclaration.ts
- src/TSTransformer/util/expressionMightMutate.ts
- src/TSTransformer/util/pointer.ts
> Remove usage of luau.MixedTable

- src/Shared/constants.ts
> Enable `--optimizedLoops` by default

- src/TSTransformer/classes/TransformState.ts
> Fix TransformState.guessVirtualPath for TS 5.3

- CHANGELOG.md
[Rendered](https://github.com/roblox-ts/roblox-ts/blob/Add-links-to-CHANGELOG.md/CHANGELOG.md)
> Add links to CHANGELOG.md

- src/TSTransformer/nodes/class/transformDecorators.ts
> Simplify decorator key lookups

- tests/src/tests/decorator.spec.ts
- tests/tsconfig.json
Adds unit tests for:
- Non-static, computed non-static, and static property decorators
- Non-static, computed non-static, and static method decorators
- Non-static & static parameter decorators
- Constructor decorators
- Class decorators
> Decorator tests
